name: Docker CI-CD Rollback Demo

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Commit SHA to deploy / rollback (leave empty to use latest)"
        required: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dhavaldevops/docker-app-with-ci-cd-rollback

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    outputs:
      short_sha: ${{ steps.sha.outputs.short_sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Get Commit SHAs
        id: sha
        run: | 
            echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            echo "full_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        run: |
          echo "${{ secrets.USER_GITHUB_TOKEN }}" | \
          docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: |
          docker build \
            -t $REGISTRY/$IMAGE_NAME:${{ steps.sha.outputs.short_sha }} \
            -t $REGISTRY/$IMAGE_NAME:${{ steps.sha.outputs.full_sha }} \
            -t $REGISTRY/$IMAGE_NAME:latest \
            .

      - name: Push Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ steps.sha.outputs.short_sha }}
          docker push $REGISTRY/$IMAGE_NAME:${{ steps.sha.outputs.full_sha }}
          docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.image_tag != '')

    environment:
      name: production
    
    steps:
      - name: Auto Deploy with Approval
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            APP_DIR="/opt/sample-rollback-app"
            IMAGE="ghcr.io/dhavaldevops/docker-app-with-ci-cd-rollback"
            STATE_FILE="$APP_DIR/state/last_good_image"
            
            cd $APP_DIR

            echo "Logging into GHCR..."
            echo "${{ secrets.USER_GITHUB_TOKEN }}" | \
            docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

            if [ "${{ github.event_name }}" = "push" ]; then
                NEW_TAG="${{ needs.build.outputs.short_sha }}"
                echo "Push event ‚Üí deploying latest build: $NEW_TAG"
            else
                NEW_TAG="${{ github.event.inputs.image_tag }}"
                if [ -z "$NEW_TAG" ]; then
                    NEW_TAG="latest"
                fi
                echo "Manual deploy ‚Üí deploying tag: $NEW_TAG"
            fi

            # Health check (polling)
            echo "Waiting for health check..."
            MAX_WAIT=60
            WAITED=0
            INTERVAL=5

            CONTAINER_ID=$(docker ps -qf "name=sample-rollback-app")

            while [ $WAITED -lt $MAX_WAIT ]; do
                HEALTH=$(docker inspect --format='{{.State.Health.Status}}' $CONTAINER_ID)
                echo "Health: $HEALTH"

                if [ "$HEALTH" = "healthy" ]; then
                echo "‚úÖ Deployment successful"
                echo "$NEW_TAG" > $STATE_FILE
                exit 0
                fi

                if [ "$HEALTH" = "unhealthy" ]; then
                    break
                fi

                sleep $INTERVAL
                WAITED=$((WAITED + INTERVAL))
            done

            #### Rollback Logic ####
            echo "‚ùå Deployment failed ‚Üí rolling back"

            if [ ! -s "$STATE_FILE" ]; then
                echo "üö® No last good image found"
                exit 1
            fi

            LAST_GOOD=$(cat $STATE_FILE)
            echo "Rolling back to $LAST_GOOD"

            IMAGE_TAG=$LAST_GOOD docker compose down
            IMAGE_TAG=$LAST_GOOD docker compose up -d

            exit 0