name: Docker CI-CD Rollback Demo

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Commit SHA to deploy (rollback supported)"
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dhavaldevops/docker-app-with-ci-cd-rollback

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set SHA
        run: | 
            echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            echo "FULL_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Login to GHCR
        run: |
          echo "${{ secrets.USER_GITHUB_TOKEN }}" | \
          docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: |
          docker build \
            -t $REGISTRY/$IMAGE_NAME:$SHA \
            -t $REGISTRY/$IMAGE_NAME:$FULL_SHA \
            -t $REGISTRY/$IMAGE_NAME:latest \
            .

      - name: Push Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$SHA
          docker push $REGISTRY/$IMAGE_NAME:$FULL_SHA
          docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy / Rollback
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            APP_DIR="/opt/sample-rollback-app"
            IMAGE="ghcr.io/dhavaldevops/docker-app-with-ci-cd-rollback"
            STATE_FILE="$APP_DIR/state/last_good_image"
            NEW_TAG="${{ github.event.inputs.image_tag }}"

            cd $APP_DIR
            echo "Logging into GHCR..."
            echo "${{ secrets.USER_GITHUB_TOKEN }}" | \
            docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

            echo "Deploying new image: $IMAGE:$NEW_TAG"
            docker pull $IMAGE:$NEW_TAG

            echo "Starting new deployment..."
            IMAGE_TAG=$NEW_TAG docker compose up -d --remove-orphans

            echo "Waiting for health check..."
            sleep 10

            CONTAINER_ID=$(docker ps -qf "name=sample-app")

            if [ -z "$CONTAINER_ID" ]; then
                echo "âŒ Container failed to start"
                FAILED=1
            else
                HEALTH=$(docker inspect --format='{{.State.Health.Status}}' $CONTAINER_ID)
                if [ "$HEALTH" != "healthy" ]; then
                    echo "âŒ Container unhealthy: $HEALTH"
                    FAILED=1
                else
                    FAILED=0
                fi
            fi

            if [ "$FAILED" = "1" ]; then
                echo "ðŸ” Rolling back..."
                LAST_GOOD=$(cat $STATE_FILE)

                IMAGE_TAG=$LAST_GOOD docker compose down
                IMAGE_TAG=$LAST_GOOD docker compose up -d

                echo "Rollback complete â†’ $LAST_GOOD"
                exit 1
            else
                echo "âœ… Deployment successful"
                echo "$NEW_TAG" > $STATE_FILE
            fi